#1-setup package skeleton
blumilksoftware/laravel-heatmap pull request #6
Opened 2024-06-24 12:16 UTC by BarTracz

Tested on Laravel application and it works. I have to add eloquent helper yet as mentioned in #2 but for now lets push it as it is. This should close #1. I need to write documentation, but I will do it after adding the eloquent helper, so I will open this as separate issue.

2024-06-24 12:55 UTC, EwelinaSkrzypacz commented on .github/workflows/check-pr-title.yml
> +      - uses: blumilksoftware/action-pr-title@e05fc76a1cc45b33644f1de51218be43ac121dd0 # v1.2.0
```suggestion
      - uses: blumilksoftware/action-pr-title@e05fc76a1cc45b33644f1de51218be43ac121dd0 # v1.2.0
      
```

2024-06-24 12:55 UTC, EwelinaSkrzypacz commented on .github/workflows/php.yml
> +        run: php vendor/bin/phpunit --configuration phpunit.xml
```suggestion
        run: php vendor/bin/phpunit --configuration phpunit.xml
        
```

2024-06-24 12:55 UTC, EwelinaSkrzypacz commented on .gitignore
> +.php-cs-fixer.cache
```suggestion
.php-cs-fixer.cache

```

2024-06-24 12:55 UTC, EwelinaSkrzypacz commented on index.php
> +            //timezone: new \Carbon\CarbonTimeZone('+2'),
Do we need this comment here?

2024-06-24 12:55 UTC, EwelinaSkrzypacz commented on phpunit.xml
> +</phpunit>
```suggestion
</phpunit>

```

2024-06-24 18:41 UTC, krzysztofrewak commented
Okay, I think there were some misunderstanding here. There's no reason to copypaste working package to new repository. What I expected was to create almost empty Laravel package that would require (in Composer) our base library. So if anyone would install `laravel-heatmap`, would get `heatmap` behind the curtain.

Please remove copypasted codebase and add `blumilksoftware/heatmap` to the Composer manifest.

2024-06-26 10:33 UTC, JakubKermes commented on composer.json
> +    "blumilksoftware/heatmap": "dev-main"
```suggestion
    "blumilksoftware/heatmap-builder": "*"
```

2024-06-26 10:36 UTC, BarTracz commented on composer.json
> +    "blumilksoftware/heatmap": "dev-main"
i overlooked this, thanks

2024-06-27 12:56 UTC, krzysztofrewak requested changes

2024-06-27 12:56 UTC, krzysztofrewak commented on composer.json
> +    "blumilksoftware/heatmap-builder": "*"
```suggestion
    "blumilksoftware/heatmap": "0.0.1"
```

2024-06-27 12:56 UTC, krzysztofrewak commented on composer.json
> +  ],
Now you can remove it.

2024-06-28 09:21 UTC, BarTracz commented on composer.json
> +    "blumilksoftware/heatmap-builder": "*"
Changed

2024-06-28 09:21 UTC, BarTracz commented on composer.json
> +  ],
Removed

2024-06-28 09:22 UTC, krzysztofrewak approved these changes

2024-06-28 09:27 UTC, JakubKermes approved these changes

2024-06-28 09:29 UTC, JakubKermes commented on composer.json
> +    "blumilksoftware/heatmap": "dev-main"
ok

2024-06-28 09:29 UTC, merged