#2 - eloquent helper
blumilksoftware/laravel-heatmap pull request #7
Opened 2024-07-03 11:58 UTC by BarTracz

Builder now allows to build heatmaps using eloquent models and collections

2024-07-04 09:12 UTC, kamilpiech97 commented on index.php
> +</html>
```suggestion
</html>

```

2024-07-04 09:12 UTC, kamilpiech97 commented on src/LaravelHeatmapBuilder.php
> +                throw new \InvalidArgumentException("The property '{$this->arrayAccessIndex}' does not exist on the given model.");
```suggestion
                throw new \InvalidArgumentException("The property '{$this->arrayAccessIndex}' does not exist on the given model.");
```
lets import that

2024-07-04 11:03 UTC, kamilpiech97 requested changes

2024-07-04 11:03 UTC, kamilpiech97 commented on index.php
> +        $now = Carbon::now();
```suggestion
```

2024-07-04 11:03 UTC, kamilpiech97 commented on index.php
> +</head>
For me better should be write tests for that.

2024-07-04 11:03 UTC, kamilpiech97 commented on index.php
> +</head>
That `index.php`, you can use locally if you need

2024-07-04 11:39 UTC, BarTracz commented
This index.php shouldn`t be there, there is one in php version already

2024-07-05 09:31 UTC, BarTracz commented
Now instead of 1 builder with many ifs to determine which operation to make, method is separated to buildFromArray, and buildFromCollection to make it easier to add new accepted data types.

2024-07-05 09:47 UTC, BarTracz commented
Tests can be added in #4(which i plan to do just after this issue), so i guess it is fine to close it without implementing any.

2024-07-05 09:55 UTC, kamilpiech97 approved these changes

2024-07-05 10:00 UTC, merged